### ISSUE TITLE
Cannot get custom card to show - are there updated install instructions?

### ISSUE THREAD

**Issue by boxgr0ve** [amaximus/garbage-collection-card#96] opened 2022-07-13 15:06 UTC
Installed using HACS - HA version Home Assistant 2022.7.3

Instructions state to add the card to the resources in configuration.yaml: however you cannot use resources: in configuration.yaml anymore

Edit Dashboard, Manage Resources contains:
"/hacsfiles/garbage-collection-card/garbage-collection-card.js?hacstag=2070182001201"

Rebooted and reinstalled multiple times but whenever creating a manual card using code it just says no card type configured.

**Comment by amaximus** [comment] 2022-07-13 15:56
You'll have to consult your configuration to see if your Lovelace runs in yaml or storage mode. The card's description refers to yaml mode. In storage mode you'll have to use the UI to add resources.

**Comment by boxgr0ve** [comment] 2022-07-13 17:22
ok managed to get card to finally display but icon isn't showing.... colours flash up when I click, but no icon?  any ideas?

Tried inserting icon: midi:trash-can but no dice - icon displays fine with a normal entity card and sensor.bin 

<img width="909" alt="Screenshot 2022-07-13 at 18 37 05" src="https://user-images.githubusercontent.com/36746869/178795993-68fa0655-2ada-4f81-80e7-6716f1751366.png">

**Comment by amaximus** [comment] 2022-07-13 19:28
The right format for icon shoud be: `icon: mdi:trash-can` and it should be defined at the sensor definition not the card.

**Comment by AlexGreenUK** [comment] 2022-07-18 01:05
@boxgr0ve Hey, Could you tell me how you got your card back. I have just updated the Garbage Collection in HACS and I think I have the same issue and the card is now not showing.

Thanks

**Comment by boxgr0ve** [comment] 2022-07-18 08:55
> @boxgr0ve Hey, Could you tell me how you got your card back. I have just updated the Garbage Collection in HACS and I think I have the same issue and the card is now not showing.
> 
> Thanks

Not sure if this is exactly what fixed it but I changed the manage resources link to just:
/hacsfiles/garbage-collection-card/garbage-collection-card.js

I ended up looking at some other custom card examples to see how they handled custom resources and they seemed to follow that - installing via the add-on added "?hacstag=2070182001201" which im not overly sure is relevant or not... seems to work for me now though!

**Comment by rbovenkampclearict** [comment] 2022-08-31 16:09
> You'll have to consult your configuration to see if your Lovelace runs in yaml or storage mode. The card's description refers to yaml mode. In storage mode you'll have to use the UI to add resources.

I have the same problem as topic starter. Can you give some more hints on how to solve?

**Comment by amaximus** [comment] 2022-09-01 07:18
@rbovenkampclearict I'm not familiar with UI mode, but generally speaking you'll have to add this card as a resource in a similar way you're doing for other custom card.

**Comment by rbovenkampclearict** [comment] 2022-09-01 09:14
That’s what i’m doing. Add manual card > fill in yaml > get error that the card is not found

**Comment by amaximus** [comment] 2022-09-01 09:32
Have you added the card via HACS?
Do you see the related directory on file system level under $[HASS_CONF}/www/community?
![hass_garbage_collection_card](https://user-images.githubusercontent.com/2511168/187881940-9150cc8c-dc00-44ee-87dd-95d026975a72.PNG)

**Comment by mgg-scudnet** [comment] 2022-10-02 08:25
Hi,
I am having the same problem. Installed the card today via HACS on HA OS v2022.9.7 OS 9.0

I am trying to integrate it with the hacs_waste_collection_schedule integration.

I have confirmed the files are present as above and also that an entry was added to the resources. Mine looks like: /hacsfiles/garbage-collection-card/garbage-collection-card.js?hacstag=2070182001201

However when I try to add the card to a dashboard using the provided examples I get the error: 

Configuration errors detected:
Custom element not found: garbage-collection-card

I just noticed in your reply you mentioned HASS_CONF - is this an environment variable that should be set? I checked in my HA terminal and I don't have that. 

Any help would be appreciated.

Thanks.

**Comment by fat115** [comment] 2022-10-02 10:14
> Hi, I am having the same problem. Installed the card today via HACS on HA OS v2022.9.7 OS 9.0
> 
> I am trying to integrate it with the hacs_waste_collection_schedule integration.
> 
> I have confirmed the files are present as above and also that an entry was added to the resources. Mine looks like: /hacsfiles/garbage-collection-card/garbage-collection-card.js?hacstag=2070182001201
> 
> However when I try to add the card to a dashboard using the provided examples I get the error:
> 
> Configuration errors detected: Custom element not found: garbage-collection-card
> 
> I just noticed in your reply you mentioned HASS_CONF - is this an environment variable that should be set? I checked in my HA terminal and I don't have that.
> 
> Any help would be appreciated.
> 
> Thanks.

Same here.
In fact, you just need to add one card at a time with this following syntax as manual card in Lovelace UI :
```
type: custom:garbage-collection-card
entity: sensor.selective_waste
icon_size: 35px
icon_color: green
hide_date: true
```
No indent, no - before type declaration.
Then it works.

**Comment by hoodja** [comment] 2022-12-09 16:30
I am having the same problem as described above. After confirming installation, existence of files, and proper config formatting in a manual card I'm left with "no card type configured".

Removing "?hacstag..." from the resource did not seem to help either.

I'm not sure how to further debug the system. I implemented a workaround using template sensors to extract the days attribute into it's own sensor for display using the entity list card.

**Comment by amaximus** [comment] 2022-12-09 18:57
@hoodja please make sure that you restart HASS after adding the card as a resource. After the HASS restart make sure you flush the browser cache.

**Comment by hoodja** [comment] 2022-12-09 22:58
Thanks for the tip @amaximus. After the browser refresh I was able to get the card working with configuration similar to above.

**Comment by amaximus** [comment] 2022-12-09 23:44
@hoodja I'm glad it's working for you.

**Closed as completed** 2023-07-14 13:27 UTC
Labels: bug
