### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by bkr1969** [amaximus/garbage-collection-card#84] opened 2021-11-09 16:08 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**
Has worked perfectly, but today, my garbage collection date, there is no icon at all. Everything else is there, just no icon.

**Screenshots**

**Environment (please complete the following information):**
 - Garbage Collection Card version: [latest - can't locate actual number]
 - Browser: Chrome
 - Browser language: English

**Additional context**

**Comment by bkr1969** [comment] 2021-11-09 22:13
Now the trash icon is back, but no recycle icon. Both configured the same apart from the actual icon.

**Comment by amaximus** [comment] 2021-11-10 11:04
Testing the newest version of the card newest HA Core the recycle button is visible (pls see attached). Maybe you'll have to clear your browser cache and reload the page.

Some user reported that restarting supervisor also helped. I'm not using the supervisor mode installation, but the simple HA Core (python virtual env), so I do not know what influence supervisor has on the frontend.
![f72c1520-7ad2-492d-ab0a-0c2aa23c45d0](https://user-images.githubusercontent.com/2511168/141102005-a18558de-f1d4-4172-8aad-85d9fb28175d.png)

**Comment by bkr1969** [comment] 2021-11-10 14:48
So I restarted supervisor and the icons came back.  Then I updated both the Fold Entity Row card and Vacuum card and reloaded the browser and they were gone again. So far restarting supervisor hasn't brought them back again.

**Comment by bkr1969** [comment] 2021-11-10 22:58
They seem to be randomly coming and going. There is nothing in the logs.
I don't think it's version related as it started yesterday when I updated to 2021.11.2, but I have since gone back to 2021.10-6 and still have the problem.

**Comment by amaximus** [comment] 2021-11-11 10:05
I'd say it's either a browser caching issue or some other component (supervisor?), but it's definitely not the card.

**Comment by bkr1969** [comment] 2021-11-11 15:23
I don't think it's browser related as it's the same problem in the app. Is there any way to dig into the supervisor and troubleshoot this?

**Comment by amaximus** [comment] 2021-11-11 16:01
I'm not familiar with the Supervisor as I'm using the HA core installation.

**Comment by mickeynygaard** [comment] 2021-11-18 21:03
I have the exact same issue. I've tried everything in regards to reconfiguring sensors, templates, etc...I had originally not updated to 2021.11.2 but just did and that made no difference...same experience, Icon is missing, in fact, most of the card is missing for me,...seems that if I by accident click the card, it...disappears?

**Comment by amaximus** [comment] 2021-11-18 21:20
@mickeynygaard you may set hide_on_click to false.

**Comment by mickeynygaard** [comment] 2021-11-18 21:26
> @mickeynygaard you may set hide_on_click to false.

I could do that, but still I have no icons… I’ve tried both the 09 HA, the 11, and both 2.0 and 1.9 of the card… I really did nothing and it just stopped working, really strange

**Comment by bkr1969** [comment] 2021-11-18 21:40
They have never returned for me.

**Comment by mickeynygaard** [comment] 2021-11-18 22:06
> They have never returned for me.

Maybe we can find something we have in common that’ll help the troubleshooting?

**Comment by amaximus** [comment] 2021-11-18 22:16
I have a HA Core installation where I cannot reproduce the fault. Some users reported the issue in a setup with supervisor. Some even mentioned that restarting the supervisor helped. I'm not familiar with the supervisor, what's its role, so I do not know how it would relate to the frontend.

**Comment by mickeynygaard** [comment] 2021-11-18 22:18
I’m running core as well, docker instance, so no supervisor for me sadly…

**Comment by bkr1969** [comment] 2021-11-18 22:32
Restarting supervisor does nothing for me.

**Comment by arigit** [comment] 2021-11-18 23:13
I noticed the same problem on 2011.11.4, the missing icon issue is only on the android app in my case. When accessing from two different laptops, the icons are still there (perhaps they got cached from before the update to 2021.11). Restarting the app, cleaning cache etc, is not fixing the problem
Also using Core, on docker on RPi4

**Comment by amaximus** [comment] 2021-11-19 11:00
Just double-checked again both on a laptop running Windows 10 with Chrome 96.0.4664.45 and on an Android 10 mobile with HomeAssistant app and they both show the icon.

![screenshot](https://user-images.githubusercontent.com/2511168/142611749-59745ac1-9951-4741-8821-ac581b189e8d.png)
![Screenshot_20211119-115346](https://user-images.githubusercontent.com/2511168/142611771-5046a1ab-fa07-4f17-92b3-1314cecd4062.png)

There must be some other aspect that is common for your setups that causes this behaviour.

**Comment by mickeynygaard** [comment] 2021-11-19 13:04
I Just tried adding a couple of cards with only the bare minimum of configuration...
The "Genbrug" (recycle) one showed an icon initially but now it's gone...Genbrug still shows a date and next time emptied, but the one for normal garbage is just a blank...

![image](https://user-images.githubusercontent.com/64093878/142627223-7d4e343b-ee96-4937-a013-f6ff91845108.png)

Are there country specific files that may be at fault? I'm from Denmark if that matters at all

**Comment by amaximus** [comment] 2021-11-19 13:10
These are not country specifics. It would be good to know at least one of your card's config.
Please also note that this card is for sensors of custom integration [Garbage Colection](https://github.com/bruxy70/Garbage-Collection/) as it expects states and attributes created by that integration.

**Comment by mickeynygaard** [comment] 2021-11-19 16:29
So I think the sensor I use is a bit different but I tried adding the Gar
![image](https://user-images.githubusercontent.com/64093878/142656243-902f3cf2-b60a-44e0-aec5-1db6d9237d6f.png)
![image](https://user-images.githubusercontent.com/64093878/142656269-4b1dc0c2-9181-404c-ba50-795b3589f0c2.png)
![image](https://user-images.githubusercontent.com/64093878/142656303-9de0248f-0fa7-4cbe-a543-2483c2f26217.png)
![image](https://user-images.githubusercontent.com/64093878/142656417-609811dd-64b1-4b35-9b11-dd56b707e4c2.png)

I downgraded the card to 1.19 earlier in a troubleshooting attempt...just updated to 1.20 and now it seems like it works...very strange :|

Thank you for your help Amaximus

**Comment by bkr1969** [comment] 2021-11-19 16:51
I'm on 1.2 and mine do not show.

**Comment by amaximus** [comment] 2021-11-20 12:30
@bkr1969 when you mention 1.2, which component were you refering to?
The latest versions are:
* for the custom card it's 1.20.0
* for the [custom integration](https://github.com/bruxy70/Garbage-Collection) it's 3.20
* for HASS Core it's 2021.11.4

**Comment by bkr1969** [comment] 2021-11-20 12:42
1.2 = 1.20.0 for the card. I am on the latest version of everything except Core is still 2021.10.6 because 2021.11.xx breaks one of my Tuya lights and no one has been able to tell me why.

**Comment by amaximus** [comment] 2021-11-20 14:06
@bkr1969 could you please provide both the sensor and the card configuration?

Icon handling was changes in HASS 2021.11, that was addressed in version 1.20.0 of the card [1]
If you are on 2021.10.x I'd recommend using version 1.19.0 of the card.

[1] https://github.com/amaximus/garbage-collection-card/releases/tag/1.20.0

**Comment by arigit** [comment] 2021-11-20 19:28
@amaximus I am using 2021.11.4, icons gone in the android app. Was working perfectly up to 2021.10.x
Card version 1.20.0

I tried downgrading to 1.19, same problem. 

Card configuration:
```
                - type: custom:garbage-collection-card
                  name: Organics
                  entity: sensor.garbage_collection_organics
                  title_size: 11px
                  icon_size: 35px
                  icon_color: green
                - type: custom:garbage-collection-card
                  name: Garbage
                  entity: sensor.garbage_collection_garbage
                  title_size: 11px
                  icon_size: 35px
                  icon_color: grey
                - type: custom:garbage-collection-card
                  name: Recyclables
                  entity: sensor.garbage_collection_recyclables
                  title_size: 11px
                  icon_size: 35px
                  icon_color: blue
```

Integration configuration

![image](https://user-images.githubusercontent.com/652673/142738657-bb5442ee-639d-4bff-addd-40b5e19b7631.png)

![image](https://user-images.githubusercontent.com/652673/142738681-5cd20ced-9c8c-455a-8f46-dbbd4f5a8318.png)



I tried removing all my customization from the card, and it didn't help. In the integration, I tried removing the icon strings, saving and reloading, it didn't help either.

**Comment by amaximus** [comment] 2021-11-21 12:48
@arigit Card version 1.20.0  should work with 2021.11.x while card version 1.19.0 should work with versions prior to 2021.11.x.

By android app do you mean the official Home Assistant app [2], right? Are you using the latest version of the android app?
Do the icons appear on the card in a web browser session?

[2] https://play.google.com/store/apps/details?id=io.homeassistant.companion.android

**Comment by bkr1969** [comment] 2021-11-21 14:59
So maybe I just need version 1.19 since I’m not upping core to 2021.11.xx yet. How to I roll that back?

**Comment by amaximus** [comment] 2021-11-21 15:12
@bkr1969 you may download file [3] and place it in ${HOME_ASSISTANT_CONF}/www/community/garbage-collection-card directory and remove the garbage-collection-card.js.gz file.

[3] https://github.com/amaximus/garbage-collection-card/blob/1.19.0/dist/garbage-collection-card.js

**Comment by arigit** [comment] 2021-11-21 17:13
@amaximus yes this is on the Android app, latest version pushed to the play store (2011.10), on android 12 (Pixel 6), I did not have any issue on my browsers (firefox on both linux and mac). I could solve the problem with the app though and make the icons re-appear, here's how:

- open the home assistant app, and go to the "App Info" menu
- Force-stop it
- go to Storage > Clear Cache 
- re launch the app

that solved the issue for me. Weirdly enough, only the icons of the garbage-collectio-card were missing, all of the other cards were fine.

**Comment by amaximus** [comment] 2021-11-22 08:15
@arigit thanks for the detailed workaround steps. This issue seemes an android application caching issue.

**Comment by mileyceberus** [comment] 2021-12-07 06:04
I also have the same issue where the icons don't appear regardless of browser type (firefox, safari, mobile, desktop). Refreshed and cleared the caches several times to no avail.

Garbage Collection Card - 1.17.2 - 1.20.0
Garbage Collection - 3.20
HACS - 1.16.0
Home Assistant - 2021.6.5

Screenshot below.

<img width="491" alt="Screen Shot 2021-12-07 at 5 04 43 pm" src="https://user-images.githubusercontent.com/84911442/144975452-a63a3319-ba91-4da4-8d5f-bd4f31a5c4ed.png">

**Comment by amaximus** [comment] 2021-12-07 08:20
@mileyceberus have you tried restarting the Supervisor? Some users reported that it fixed the icon issue.
In a plain HA Core installation there is no Supervisor and the issue doesn't appear pointing to a caching issue in another component (I don't know what's the role of Supervisor and what are its effects on UI).

Try to restart the Supervisor and get back to me with results.

**Comment by mileyceberus** [comment] 2021-12-07 08:49
I have actually been restarting HA every time I installed a different version of your card. In any case, I have just restarted HA again and still cannot see the icons (firefox, safari, desktop, iphone, ipad).

Interestingly, I can see the outline of the icon when I click on one of the garbage sensors (see below),

<img width="497" alt="Screen Shot 2021-12-07 at 7 47 01 pm" src="https://user-images.githubusercontent.com/84911442/144996525-3638c6f4-0983-4cf6-8a3c-bb17df76290f.png">

I am not sure if the icons were broken after upgrading bruxy70's sensors as nothing is shown on the logs.

**Comment by amaximus** [comment] 2021-12-07 08:57
@mileyceberus Could you please upgrade HomeAssistant to latest? Version 1.20.0 of the card supports icons as per 2021.11 (there were some changes in this release related to how icons are handled).
If you don't want to upgrade HASS to 2021.11.x please downgrade the card to 1.19.0 [1]. That version supports the way icons are handled in HASS prior to 2021.11.

[1] https://github.com/amaximus/garbage-collection-card/releases/tag/1.19.0

**Comment by mileyceberus** [comment] 2021-12-07 08:59
I'll upgrade HA to the latest version assuming that it's fixed the issue with Xiaomi sensors.

PS. I installed every version of your card (1.17.2 - 1.20.0) but couldn't get the icons to display. Was working perfectly previously.

**Comment by mileyceberus** [comment] 2021-12-07 09:21
Thanks, the icons are visible on desktop(s) and iPad(s) when I upgraded HA to 2021.11.5. However, they are missing on my iPhone(s). Unsure if this is a frontend HA bug or not (https://github.com/home-assistant/frontend/issues/9956).

**Comment by pwae** [comment] 2022-01-16 13:53
With 2021.12.9 I'm seeing the same as what @mileyceberus did in [this comment](https://github.com/amaximus/garbage-collection-card/issues/84#issuecomment-987701180
) 
I use [https://github.com/mampfes/hacs_waste_collection_schedule](https://github.com/mampfes/hacs_waste_collection_schedule) with a custom feed.
The icon itself shows up on the entities list (see below), but not on the lovelace ui with this card (second screenshot below).

![Screenshot_20220117_005223](https://user-images.githubusercontent.com/252082/149662908-8350237d-9e7c-4025-bb53-e4130c3b3f10.png)
![Screenshot_20220117_005244](https://user-images.githubusercontent.com/252082/149662920-c5faa175-198f-4a44-95df-3543d559ca8f.png)

Card Config:
```
      - type: custom:garbage-collection-card
        entity: sensor.next_recycling_collection
        icon_size: 25px
        icon_color: '#dbdb6b'
        hide_before: 6
        hide_date: true
      - type: custom:garbage-collection-card
        entity: sensor.next_garbage_collection
        icon_size: 25px
        icon_color: blue
        hide_date: true
      - type: custom:garbage-collection-card
        entity: sensor.next_green_collection
        icon_size: 25px
        icon_color: green
        hide_before: 6
        hide_date: true

```

**Comment by amaximus** [comment] 2022-01-19 18:36
@pwae please note that this card - as mentioned at the beginning of the Readme - relies on garbage collection custom component [1], meaning that expects state value and attributes as provided by [1].

When used with [1] the card works as expected:

![garbage](https://user-images.githubusercontent.com/2511168/150193054-11f37032-1796-4bf5-b072-17450931c8e5.png)

[1] https://github.com/bruxy70/Garbage-Collection/

**Comment by pwae** [comment] 2022-01-20 06:53
> @pwae please note that this card - as mentioned at the beginning of the Readme - relies on garbage collection custom component [1], meaning that expects state value and attributes as provided by [1].

Apologies. the other addon said it supposed this card as well. But i've noticed it does, but with some additional work that i missed before. So I'll sort that out.

Thanks and apologies again!

**Closed as completed** 2023-07-14 13:26 UTC
Labels: bug
